# Generated by Django 4.1.1 on 2022-10-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mcompany_mdepartment_temployee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcompany',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mcompany',
            name='created_user_id',
        ),
        migrations.RemoveField(
            model_name='mcompany',
            name='delete_status',
        ),
        migrations.RemoveField(
            model_name='mcompany',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mcompany',
            name='updated_user_id',
        ),
        migrations.RemoveField(
            model_name='mdepartment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mdepartment',
            name='created_user_id',
        ),
        migrations.RemoveField(
            model_name='mdepartment',
            name='delete_status',
        ),
        migrations.RemoveField(
            model_name='mdepartment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mdepartment',
            name='updated_user_id',
        ),
        migrations.RemoveField(
            model_name='temployee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='temployee',
            name='created_user_id',
        ),
        migrations.RemoveField(
            model_name='temployee',
            name='delete_status',
        ),
        migrations.RemoveField(
            model_name='temployee',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='temployee',
            name='updated_user_id',
        ),
    ]
