# Generated by Django 4.1.2 on 2022-10-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_mcompany_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="temployee", name="age",),
    ]
